export const CREATE_NEW_BOARD = 'CREATE_NEW_BOARD';
export const CREATE_NEW_LIST = 'CREATE_NEW_LIST';
export const CREATE_NEW_TASK = 'CREATE_NEW_TASK';
export const UPDATE_LISTS = 'UPDATE_LISTS';
export const TASK_CHECKED = 'TASK_CHECKED';
export const UPDATE_LISTS_AND_TASKS = 'UPDATE_LISTS_AND_TASKS';
export const DELETE_LIST = 'DELETE_LIST';
